# Generated by Django 4.2.13 on 2024-06-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(upload_to='audio/')),
                ('processed_audio', models.FileField(blank=True, null=True, upload_to='processed_audio/')),
            ],
        ),
    ]
